### ISSUE TITLE
简繁转换

### ISSUE THREAD

**Issue by zxlvera** [yanhuacuo/98wubi#2]
试着用 `Ctrl + Shift + F` 转换繁体但没显示出来。如`车` → `車` 。打 `lghh`才显示出来。
![image](https://user-images.githubusercontent.com/17290983/140030746-f959c7a8-bf04-465b-a45a-bb4aa8fde591.png)

**Comment by zxlvera** [comment]
安装最新版本后就行了，谢谢

**Comment by yanhuacuo** [comment]
其实是因为 opencc 的二进制 ocd 词典不跨平台的原因（提供的是 linux 上的 ocd）。本档作为 opencc 配置的 schema 样板，永久存档，不再更新。新版配置文件，转部基于 lua 实现。

你可以在 [软件分享](https://github.com/yanhuacuo/98wubi-tables/tree/master/%E8%BE%93%E5%85%A5%E6%B3%95%E8%BD%AF%E4%BB%B6) 里找到相关软件，或者在 [配置分享](https://github.com/yanhuacuo/98wubi-weasel) 中查看新的配置文件。
