### ISSUE TITLE
希望跟五筆小築取得聯繫

### ISSUE THREAD

**Issue by ejmoog** [yanhuacuo/98wubi#3]
五筆小築的成員你們好，我是「九八五筆網頁版」的作者。

由於之前跟你們無法取得聯繫，因此我希望你們下架「九八五筆網頁版」，並刪除「天蒼人頡」的友情鏈接。

未來如果你們仍有合作的想法，歡迎跟我聯絡。

**Comment by yanhuacuo** [comment]
不好意思，刚出院，失联了这段时间。
已经去除了，感谢付出。
https://wubi98.github.io/
